name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: "Lint Code"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: "Run go vet"
        run: go vet ./...

  test:
    name: "Run Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "🔧 Setup Go (with Cache)"
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: "Execute Golang Tests"
        run: go test ./...

  build:
    name: "Build Binaries"
    runs-on: ubuntu-latest
    needs:
      - lint
      - test
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v4

      - name: "Setup Go"
        uses: actions/setup-go@v5
        with:
          cache: true
          go-version-file: go.mod

      - name: "Build all commands"
        run: |
          go build ./cmd/lazysound
